#!/bin/bash

# WORKFLOW_DEFINITION_FILE=task-sets/example-workflow.empty.json
# WORKFLOW_DEFINITION_FILE=task-sets/example-workflow.001.json
WORKFLOW_DEFINITION_FILE=task-sets/example-workflow.002.json
# WORKFLOW_DEFINITION_FILE=task-sets/task-set.8k.json

HOST_PORT=localhost:8080

usage()
{
	echo "Usage: $0 [-hv] [-H <host:port>] [-f <workflow-file>]"
	echo
	echo "  -h  Display this help"
	echo "  -H  Configure the <host:port> of the URL to which the workflow will be sent"
	echo "  -f  Read the workflow definition from the specified file (supports *.gz and *.bz2 compression)"
	echo "  -v  Verbose curl output"
}

while getopts "hH:f:v" arg
do
	case "$arg" in
		h)
			usage
			exit 0
			;;

		f)
			WORKFLOW_DEFINITION_FILE="${OPTARG}"
			;;

		H)
			HOST_PORT="${OPTARG}"
			;;

		v)
			CURL_OPTS=("${CURL_OPTS[@]}" -v)
			;;

		*)
			usage >&2
			exit 1
			;;
	esac
done

READ_FILE_CMD="cat"

case "${WORKFLOW_DEFINITION_FILE}" in
	*gz)
		READ_FILE_CMD="zcat"
		;;

	*bz2)
		READ_FILE_CMD="bzcat"
		;;
esac
		

"${READ_FILE_CMD}" "${WORKFLOW_DEFINITION_FILE}" | \
	curl "${CURL_OPTS[@]}" -X POST -H 'Content-Type: application/json' --data-binary @- "http://${HOST_PORT}/injector/workflow"
