#!/bin/bash

# DATA_FILE=example-workflow.001.json
DATA_FILE=example-workflow.002.json

DATA="$(< ${DATA_FILE})"

curl -v -X POST -H 'Content-Type: application/json' --data "${DATA}" http://localhost:8001/injector/workflow
